      - name: Delay before deployment
        run: sleep 30
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_93D462A1B0C94ECEBE7161377FF247EA }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_7C69C46A2EAA47748551A53F8674A1A9 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_DDB73B1A748747CF8982C6182AE7AA01 }}

      # ✅ Add this delay step
      - name: Delay before deployment
        run: sleep 30

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'jhello'
          slot-name: 'Production'
